apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: snes-http
  selfLink: /api/v1/namespaces/default/services/snes-http
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31228
  selector:
    app: snes
    tier: frontend
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
