version: '3'

services:
    frontend:
        build: ./frontend/
        restart: always
        ports:
          - 8080:80

    backend:
        build: ./backend/
        restart: always
        ports:
#          - 8000:8000
# 8000:8000 Can be commented out when dev is done
# Uncomment if you want to test the backend directly
